const initialAnimals = [
    { id: 1, name: "Buddy", age: 3, species: "Dog", breed: "Labrador", color: "Golden", description: "Friendly and playful.", photo: "https://images.unsplash.com/photo-1529831129093-0fa4866281ee?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { id: 2, name: "Milo", age: 2, species: "Cat", breed: "Siamese", color: "Cream", description: "Loves cuddles.", photo: "https://images.unsplash.com/photo-1568152950566-c1bf43f4ab28?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { id: 3, name: "Charlie", age: 1, species: "Dog", breed: "Beagle", color: "Brown", description: "Energetic and curious.", photo: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { id: 4, name: "Luna", age: 4, species: "Rabbit", breed: "Mini Lop", color: "White", description: "Calm and affectionate.", photo: "https://images.unsplash.com/photo-1533514114760-4389f572ae26?q=80&w=1936&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { id: 5, name: "Lucy", age: 2, species: "Cat", breed: "Persian", color: "Grey", description: "Independent and elegant.", photo: "https://images.unsplash.com/photo-1585137173132-cf49e10ad27d?q=80&w=1972&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { id: 6, name: "Daisy", age: 1, species: "Dog", breed: "Poodle", color: "White", description: "Loyal and intelligent.", photo: "https://images.unsplash.com/photo-1555325084-b068599743c9?q=80&w=1950&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
    { "id": 7, "name": "Max", "age": 5, "species": "Dog", "breed": "German Shepherd", "color": "Black and Tan", "description": "Protective and loyal.", "photo": "https://via.placeholder.com/150" },
    { "id": 8, "name": "Bella", "age": 3, "species": "Cat", "breed": "Maine Coon", "color": "Brown", "description": "Affectionate and gentle.", "photo": "https://via.placeholder.com/150" },
    { "id": 9, "name": "Rocky", "age": 4, "species": "Dog", "breed": "Bulldog", "color": "Brindle", "description": "Calm and courageous.", "photo": "https://via.placeholder.com/150" },
    { "id": 10, "name": "Cleo", "age": 2, "species": "Cat", "breed": "Bengal", "color": "Spotted", "description": "Energetic and vocal.", "photo": "https://via.placeholder.com/150" },
    { "id": 11, "name": "Simba", "age": 1, "species": "Rabbit", "breed": "Lionhead", "color": "Golden", "description": "Curious and fluffy.", "photo": "https://via.placeholder.com/150" },
    { "id": 12, "name": "Shadow", "age": 3, "species": "Cat", "breed": "Bombay", "color": "Black", "description": "Mysterious and sleek.", "photo": "https://via.placeholder.com/150" },
    { "id": 13, "name": "Buster", "age": 6, "species": "Dog", "breed": "Boxer", "color": "Fawn", "description": "Playful and energetic.", "photo": "https://via.placeholder.com/150" },
    { "id": 14, "name": "Ginger", "age": 4, "species": "Cat", "breed": "Abyssinian", "color": "Ruddy", "description": "Agile and lively.", "photo": "https://via.placeholder.com/150" },
    { "id": 15, "name": "Poppy", "age": 1, "species": "Rabbit", "breed": "Dutch", "color": "Black and White", "description": "Sweet and docile.", "photo": "https://via.placeholder.com/150" },
    { "id": 16, "name": "Rex", "age": 2, "species": "Dog", "breed": "Dalmatian", "color": "Black and White", "description": "Energetic and unique.", "photo": "https://via.placeholder.com/150" },
    { "id": 17, "name": "Coco", "age": 3, "species": "Cat", "breed": "Ragdoll", "color": "Cream and Brown", "description": "Relaxed and loving.", "photo": "https://via.placeholder.com/150" },
    { "id": 18, "name": "Nala", "age": 2, "species": "Rabbit", "breed": "Rex", "color": "Grey", "description": "Soft and gentle.", "photo": "https://via.placeholder.com/150" },
    { "id": 19, "name": "Zeus", "age": 5, "species": "Dog", "breed": "Husky", "color": "Grey and White", "description": "Strong and adventurous.", "photo": "https://via.placeholder.com/150" },
    { "id": 20, "name": "Mittens", "age": 1, "species": "Cat", "breed": "American Shorthair", "color": "Tabby", "description": "Curious and playful.", "photo": "https://via.placeholder.com/150" },
    { "id": 21, "name": "Fiona", "age": 4, "species": "Rabbit", "breed": "Angora", "color": "White", "description": "Fluffy and elegant.", "photo": "https://via.placeholder.com/150" },
    { "id": 22, "name": "Hunter", "age": 3, "species": "Dog", "breed": "Golden Retriever", "color": "Golden", "description": "Friendly and dependable.", "photo": "https://via.placeholder.com/150" },
    { "id": 23, "name": "Lola", "age": 2, "species": "Cat", "breed": "Scottish Fold", "color": "Blue", "description": "Quiet and affectionate.", "photo": "https://via.placeholder.com/150" },
    { "id": 24, "name": "Pepper", "age": 1, "species": "Rabbit", "breed": "Holland Lop", "color": "Black", "description": "Playful and cuddly.", "photo": "https://via.placeholder.com/150" },
    { "id": 25, "name": "Oscar", "age": 2, "species": "Dog", "breed": "Cocker Spaniel", "color": "Golden", "description": "Gentle and loyal.", "photo": "https://via.placeholder.com/150" },
    { "id": 26, "name": "Smokey", "age": 4, "species": "Cat", "breed": "Russian Blue", "color": "Grey", "description": "Calm and regal.", "photo": "https://via.placeholder.com/150" },
    { "id": 27, "name": "Bambi", "age": 3, "species": "Rabbit", "breed": "Netherland Dwarf", "color": "Brown", "description": "Small and lively.", "photo": "https://via.placeholder.com/150" },
    { "id": 28, "name": "Duke", "age": 5, "species": "Dog", "breed": "Rottweiler", "color": "Black and Tan", "description": "Confident and watchful.", "photo": "https://via.placeholder.com/150" },
    { "id": 29, "name": "Whiskers", "age": 1, "species": "Cat", "breed": "Turkish Angora", "color": "White", "description": "Elegant and curious.", "photo": "https://via.placeholder.com/150" },
    { "id": 30, "name": "Hazel", "age": 2, "species": "Rabbit", "breed": "Harlequin", "color": "Orange and Black", "description": "Charming and cheerful.", "photo": "https://via.placeholder.com/150" },
    { "id": 31, "name": "Riley", "age": 3, "species": "Dog", "breed": "Border Collie", "color": "Black and White", "description": "Intelligent and active.", "photo": "https://via.placeholder.com/150" },
    { "id": 32, "name": "Toby", "age": 2, "species": "Dog", "breed": "Shih Tzu", "color": "White and Brown", "description": "Affectionate and alert.", "photo": "https://via.placeholder.com/150" },
    { "id": 33, "name": "Sassy", "age": 1, "species": "Cat", "breed": "Oriental Shorthair", "color": "Lilac", "description": "Vocal and quirky.", "photo": "https://via.placeholder.com/150" },
    { "id": 34, "name": "Willow", "age": 4, "species": "Rabbit", "breed": "Satin", "color": "Brown", "description": "Calm and silky.", "photo": "https://via.placeholder.com/150" },
    { "id": 35, "name": "Jake", "age": 5, "species": "Dog", "breed": "Corgi", "color": "Red and White", "description": "Friendly and adventurous.", "photo": "https://via.placeholder.com/150" },
    { "id": 36, "name": "Mango", "age": 2, "species": "Cat", "breed": "Manx", "color": "Orange", "description": "Energetic and playful.", "photo": "https://via.placeholder.com/150" }
  ];

export default initialAnimals;